defmodule AshEmployeeApp.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:employees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :age, :bigint, null: false
      add :salary, :bigint, null: false
      add :department_id, :uuid, null: false
    end

    create table(:departments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:employees) do
      modify :department_id,
             references(:departments,
               column: :id,
               name: "employees_department_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:departments) do
      add :name, :text, null: false
    end
  end

  def down do
    alter table(:departments) do
      remove :name
    end

    drop constraint(:employees, "employees_department_id_fkey")

    alter table(:employees) do
      modify :department_id, :uuid
    end

    drop table(:departments)

    drop table(:employees)
  end
end
